### ISSUE TITLE
Bug: ETA not rendering correctly in milestone cards for YYYYQN

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/Starmaps#108]
Error description:
ETA is entered correctly in the source github issue but does not render correctly in the milestone card

Steps to recreate: 
- Enter github.com/filecoin-project/bacalhau/issues/1150 in starmaps search or go to: https://www.starmaps.app/roadmap/github.com/filecoin-project/bacalhau/issues/1150
- Click on milestone card
- See broken ETA in child milestone cards

<img width="1369" alt="Screen Shot 2022-11-16 at 12 19 50 PM" src="https://user-images.githubusercontent.com/58958327/202286658-7f7caab2-a4c2-46e6-a3e6-9cb96f178e4a.png">

**Comment by SgtPooki** [comment]
@whizzzkid would you mind taking this?

**Comment by juliaxbow** [comment]
Looking into this more this may be because the eta is entered as "ETA" vs "eta" ? Can we make this _not_ case sensitive?
