### ISSUE TITLE
Include link to GitHub source on landing / user guide page

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/StarMaps#114]

**Comment by SgtPooki** [comment]
@juliaxbow can you clarify that the ask here is to 

> Link to https://github.com/pln-planning-tools/Starmaps from https://github.com/pln-planning-tools/Starmaps/blob/main/User%20Guide.md

If so, is something like https://github.blog/2008-12-19-github-ribbons/ what we want? Or just an update to the `User Guide.md` file at the top/bottom to link to the repo?

**Comment by juliaxbow** [comment]
I was thinking it could look the same as the "View in Github (ICON)" link that we have on all other pages
