### ISSUE TITLE
http:// required for github url parsing

### ISSUE THREAD

**Issue by momack2** [pln-planning-tools/Starmaps#122]
the starmap tool should work on a github URL that is missing parameters. 
- Right now it only works with http://github.com/ipfs/roadmap/issues/96

It should work with any of:
- `github.com/ipfs/roadmap/issues/96`
- `ipfs/roadmap/issues/96`

If it gets a URL it can't parse - it should show an error in a butter bar - not just show nothing

**Comment by SgtPooki** [comment]
What is a butter bar

**Comment by momack2** [comment]
The little rectangle bar that pops up with errors on mobile / desktop (ex
the default error pop up in bootstrap)
