### ISSUE TITLE
Top timeline seems to be off

### ISSUE THREAD

**Issue by vmx** [pln-planning-tools/StarMaps#141]
When I render my roadmap: https://www.starmaps.app/roadmap/github.com/filecoin-project/rust-fil-proofs/issues/1644 the timeline at the top 
![image](https://user-images.githubusercontent.com/42839/202719914-ba806e76-ad34-4744-9d85-7fbf661537d0.png)
seems to be off a bit. I'd expect to match the ETAs of the milestones. This means that I would e.g. expect "October 2022" to read "March 2023".

**Comment by SgtPooki** [comment]
I'm looking into this as part of #135
