### ISSUE TITLE
Make simple and detailed view deep-linkable

### ISSUE THREAD

**Issue by vmx** [pln-planning-tools/StarMaps#142]
For my team the simple view doesn't provide much information:

![image](https://user-images.githubusercontent.com/42839/202722100-cbd9c41a-690b-47b0-accd-9a700a059c0c.png)

The detailed view is way better:

![image](https://user-images.githubusercontent.com/42839/202722228-b3a85b29-efcb-4268-a747-8b7529221aff.png)

But currently there's no way for me to link to the detailed view directly.

Kind of related. With having a direct link, it could make the "Switch to detail/simple view" toggle a proper link, so you could even open it in a new tab.

**Comment by SgtPooki** [comment]
We can add this back easily. It used to be deep-linkable, but I wanted it to be client-side for rendering the change, expecting this issue to pop up when someone expressed the need. Also mentioned in #145 

The key thing I want to make sure we do is leave the rendering to the client side, so we should use hash routing for the deeplink.
