### ISSUE TITLE
Update Favicon

### ISSUE THREAD

**Issue by whizzzkid** [pln-planning-tools/StarMaps#144]
Right now the favicon shows up as `nikas`: https://github.com/pln-planning-tools/StarMaps/blob/main/public/nikas.svg

We need to change this to StarMaps. Any other inputs @juliaxbow?

**Comment by SgtPooki** [comment]
We could just use the existing SVG until #70 is resolved

**Comment by SgtPooki** [comment]
putting status/pending until @juliaxbow can supply a favicon.ico
