### ISSUE TITLE
Error log should default to unfurled state

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/StarMaps#155]
Current: 
- When there are errors with github issues that prevent them from rendering on starmaps, a collapsible error log appears at the top of the timeline page. 
- The error log is collapsed by default which has resulted in at least one user not knowing where to discover what went wrong with rendering

Desired:
- Error log should be unfurled by default
- This requires the user to view the errors and then make the decision to collapse the error log

**Comment by SgtPooki** [comment]
easy update
