### ISSUE TITLE
bug: today line text overlaps header labels on smaller screens

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/StarMaps#214]
see https://github.com/pln-planning-tools/StarMaps/pull/211#pullrequestreview-1198790323 and:

![image](https://user-images.githubusercontent.com/1173416/204734788-9e2a2a58-61a5-4d53-808c-d8df715f3fa9.png)

**Comment by juliaxbow** [comment]
+1. Sent the below to Dan over Slack with some addt'l considerations for post-mvp (edited for clarity)

>Thoughts:
> - agree that we can reduce text size, though that might look a little funky if we did it small enough so that even the longest date text was always on one line.
> - If we do change text size, I’d love to change the size of the title and “today” by the same %. 
> - Speaking of, i think we can decrease the size of the today marker (and nothing else) without it looking weird and place it in between tabs and the start of the timeline
>      - on top of ^ that, can the roadmap area shift down at all to accommodate the multiple lines of date text? I.e everything would shift down instead of up, which appears to be happening? Can't say for certain since there is one single-row date that is top aligned. Either way the hope would be to allow the today marker to rest neatly on top. This combined with slightly smaller text (whatever captures most dates) could be our best bet
