### ISSUE TITLE
bug: nextjs throws application banner anytime we do `console.error`

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/StarMaps#216]
Remove all `console.errors` prior to EOD 2022-11-30

**Comment by djmcquillan** [comment]
@SgtPooki @whizzzkid should the error boundary component and next error handling prevent this from occurring in a prod build

**Comment by SgtPooki** [comment]
The error boundary should capture it if the error occurs within direct children. If the error is uncaught in nested children it wont
