### ISSUE TITLE
feat: on mobile, show a message at the top that says this app requires desktop or a large screen

### ISSUE THREAD

**Issue by tinytb** [pln-planning-tools/StarMaps#221]
Until StarMaps supports mobile, a small message inviting users to go to their desktop or larger screen device may be helpful. Otherwise people may wonder if it's something wrong with their device (do I need to refresh?), or a temporary glitch. A short, simple message would clarify that this is a known issue and mobile is not supported.

**Comment by juliaxbow** [comment]
This is being discussed in #136. Think we can close this issue

**Comment by SgtPooki** [comment]
duplicate of #136
