### ISSUE TITLE
ETA field is not being required

### ISSUE THREAD

**Issue by wilkyr31d** [pln-planning-tools/Starmaps#36]
ETA field should be required on all issues, except when navigating directly to the issue as the root node of the graph.

**Comment by SgtPooki** [comment]
I imagine this will cause some problems with the nesting of issues. We need some way to determine whether an issue is allowed to be viewed "directly" or only as a child. 

I guess the major checks require here are

### issue as root
* No ETA (success state)
* Has ETA (success state)

### Issue as child
* No ETA (failure state)
* Has ETA (success state)

So in the only failure state above -- a root issue has a child that is lacking an ETA -- what are we to do?

@wilkyr31d to clarify

**Comment by wilkyr31d** [comment]
We're potentially re-doing design here, but maybe that's okay. Backing up, after actually trying to add real roadmaps recently, I realized that there's two cases where putting in an ETA feels silly:
1) the root issue of the graph (the "roadmap" issue)
2) the first level children of that, IF I only intend to use that issue as a category (horizontal band) in the detail view (I did this with the themes we had defined for Kubo work, and then put the milestones under those)

So, given this, I'm going to propose a few options:
1) Do nothing; require ETA on all items. This is easiest, and even if the UX is kind of bad it's something we can relax later.
2) Do not require ETA on the root node, but require it everywhere else. Since the root node is the top of the navigation hierarchy I think this is fine; if you tried to load a roadmap where that node is a child and it didn't have an ETA it would fail; so it's not about that specific issue but more about the current context. Requiring it everywhere else means we don't have to think about placement of issues without ETAs on the timeline
3) Don't require ETA's anywhere. For nodes that need to be rendered on the timeline, just put anything without an ETA at the very beginning (or end I suppose), and the tile itself would not show an ETA which is a good visual cue that's what going on. In some ways I like this best. It provides a lot of flexibility in creating the kinds of views you might want to build, and puts a lot of control (and ability to screw up) in the user's hands. OTOH, I think it's going to be really hard to reverse this decision later as it's a breaking change.

Thoughts? @SgtPooki @juliaxbow

**Comment by wilkyr31d** [comment]
Putting this at P0 until we clarify what we want and can then re-assess

**Comment by SgtPooki** [comment]
@wilkyr31d I think with P0 deadline in mind, we should stick with option 1.

**Comment by wilkyr31d** [comment]
We decide on a whole different path: https://filecoinproject.slack.com/archives/C0418TBQ9CH/p1668202769477109

Tracking the error condition here through #51 - can close this.
