### ISSUE TITLE
Click-through on milestone with no children shouldn't be allowed

### ISSUE THREAD

**Issue by wilkyr31d** [pln-planning-tools/StarMaps#62]
Currently you can click-through on a milestone with no children, which results in an empty page with a message "not found"

**Comment by wilkyr31d** [comment]
@SgtPooki - I don't think this is error handling issue; this is a navigation issue. We don't need a better error message, we need to disable ability to click to "zoom in" on an issue that doesn't have children.

**Comment by SgtPooki** [comment]
@wilkyr31d yes, I agree, but this is an error state that needs to be handled by blocking, versus an error state that needs to be handled by rendering an error. This is a UX Gotcha that is not currently handled.

**Comment by juliaxbow** [comment]
Description: 
In "Detailed View," for at least one roadmap, milestones with no children are clickable and lead to an error (after appearing to show the parent milestone in "Overview")

Recreate:
- Visit https://www.starmaps.app/roadmap/github.com/cryptonetlab/roadmap/issues/20#detail
- Click on "have 5 or more network grants" tile
- See error

What should happen:
- Milestone cards with no children shouldn't be clickable

See vid: 

https://user-images.githubusercontent.com/58958327/204042309-08dccc39-5213-45c8-bd8b-d6a659b828ff.mov
