### ISSUE TITLE
Set up site in PL-owned hosting environment and apply acquired domain name

### ISSUE THREAD

**Issue by wilkyr31d** [pln-planning-tools/Starmaps#64]

**Comment by SgtPooki** [comment]
There are some action items required here by multiple people in order to proceed:

1. @wilkyr31d 
    - [ ] provide DNS information to us privately so we can [update settings in vercel](https://vercel.com/docs/concepts/projects/domains/add-a-domain) 
        * I've sent you screenshots privately of the DNS configurations that need updated, but if you provide me access I can do that.
2. @AlexxNica 
    - [ ] clarify what settings/features we would need to configure in vercel, as I was able to get the site up and running and connected to our new vercel team easily.
         - [ ] Do we **need** to "transfer" things?

**Comment by SgtPooki** [comment]
Pinged site-delivery team on slack and also opened protocol/infra#1009. Hopefully we have no further actions regarding domain name, but they should get back to me with any changes necessary

**Comment by SgtPooki** [comment]
calling this done!
