### ISSUE TITLE
Milestone issues should support different eta formats

### ISSUE THREAD

**Issue by wilkyr31d** [pln-planning-tools/Starmaps#67]
Need to support:
- dates (already supported)
- months
- quarters.

@wilkyr31d is going to update user guide with exact syntax and comment back here when done

**Comment by SgtPooki** [comment]
@wilkyr31d we need to be careful about scenarios where this can bite us:

1. Roadmap showing issues with the following ETAs have multiple possible visual representations: [Q4, Q1, Q2, Q4, Q1]
    * Are they all the same year?
    * Are they spanning multiple years?
    * How do we tell? Removing dates means the syntax needs to cover this

**Comment by SgtPooki** [comment]
Also, is this a P0 thing...?

**Comment by wilkyr31d** [comment]
User guide has already been updated with the spec for data format
