### ISSUE TITLE
Add breadcrumb trail with links to easily return to parent/grandparent roadmap

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/StarMaps#69]
See prototype recording.

1. Click on a milestone to view that milestone and subsequent children milestones
2. Breadcrumb trail should appear as header, with parent milestones clickable links to return to parent roadmap

https://user-images.githubusercontent.com/58958327/201188547-e986e036-35de-4f76-aef3-0e3a8026c364.mov

**Comment by wilkyr31d** [comment]
I love this feature. That said, I'm a little nervous putting this as a P0 as it feels like a big additional functionality and just don't want to risk any other P0's on this tight timeline. Personally, I'd probably push for P2 even, but want to hear why you're feeling P0 here.
cc @juliaxbow @whizzzkid @SgtPooki

**Comment by juliaxbow** [comment]
For MVP is your pushback on:
1. the breadcrumb trail itself (which shows users how they got to the current page)?
or 
2. being able to navigate directly from the breadcrumb trail (which saves users from having to backpedal each step and allows them to skip back to the parent node)?

I think it's a huge win for navigation for the reasons mentioned above. At the very least having #1 satisfied will help usability, especially in the event that a roadmap has more than 3 generations/subsequent milestones that a user can get lost in.

If a breadcrumb trail isn't something easily accomplished, though, I'd be comfortable moving this to P1 and reverting back to having a "Back to Parent Roadmap" link. But would really push for keeping the trail! I'd prioritize this over any visual design suggestions, even.

**Comment by SgtPooki** [comment]
I agree with the benefits but the number of P0 already existing makes this more of a P1 for me for now. Hopefully we'd have time for this but I think we could tackle this after other base functionality things are done. 

Also, this seems related to #44. Closing #44 in favor of this one since there is more detail here.

**Comment by SgtPooki** [comment]
@whizzzkid @AlexxNica what are your estimates for this ?

**Comment by SgtPooki** [comment]
I'm going to bump this down in priority for now, because the effort is not trivial

**Comment by maxscience** [comment]
Yes this is definitely a need!

**Comment by SgtPooki** [comment]
bumping this down in priority as we have other things we really need to get done

**Comment by juliaxbow** [comment]
Considering other high prio items, do we have an ETA for this?

**Comment by SgtPooki** [comment]
I think I can grab this tomorrow and give it a go. ETA probably friday

**Comment by juliaxbow** [comment]
Also sent in slack:
**Proposal**
- I propose a breadcrumb trail above the main header
- Header should also sit above the error log where applicable
- Per @SgtPooki 's suggestion, we should still consider ellipses after ~10 characters in the new breadcrumb trail. 
- Note: Header is no longer a link 

**Note on mobile:**
- (once we get there) in mobile view, the "trail" would instead link to just the previous page.  Will address in the thread around mobile responsiveness. 

**Details**
Link text: 16pt Medium; rgba(73, 135, 189, 1); underline on hover state
Forward slash: rgba(21, 39, 54, 1)

Quick mock-up to show how this would look:

https://user-images.githubusercontent.com/58958327/204875927-26bcc752-fb53-4994-98de-d83bb6411b17.mov


@whizzzkid GREAT callout. And actually the bigger issue that this made me consider is the scenario where a child milestone is linked in multiple parent issues (can't say with certainty that this won't happen; I think even in the Ignite roadmap there's an instance of this). Does anyone know what would happen in the system then? Would it break anything by showing two different roadmaps? 

Our options:
(A) Show only the input issue (whatever was entered into search bar) as start of the breadcrumb trail as @whizzzkid  described above
>Breadcrumbs:

when visited directly: no breadcrumbs
when visited from A: A > D > E
when visited from B: B > C > E

(B) Show the full trail, (so even if "C" is the input show A > B > C  > D)

I'm inclined to go with the second option, though again it doesn't solve for the issue described above, wherein a child milestone is linked in multiple issues. Would like to know what would happen in that scenario with current code if anyone knows.

@whizzzkid sounds like you feel differently so happy to hear alternatives.

Ultimately I don't see this issue completely defeating the purpose of a breadcrumb trail since it's replicating GitHub in a way ---allowing the user to zoom out to the root issue. It's also important because of the current lack of visibility into system status. If I hit "back" from my browser, because of the delay and lack of skeleton loading it's hard to know if the tool's working correctly, or what I'm being taken back to

**Comment by SgtPooki** [comment]
@juliaxbow from your last mockup, i'm planning on making a few changes:

1. No "Home", we have the starmaps logo for that
2. No rendering of breadcrumbs above title if they don't exist (we should have a placeholder to use)
3. No rendering of the currently view issue's title in the breadcrumbs (showing the title twice is unnecessary and showing it as a link is not useful)

**Comment by juliaxbow** [comment]
>No rendering of the currently view issue's title in the breadcrumbs (showing the title twice is unnecessary and showing it as a link is not useful)

I'm supportive of all changes except for this one. It's standard to include the current webpage in the breadcrumb trail (slightly outdated but look at some of the screenshots [here](https://www.nngroup.com/articles/breadcrumbs/)). Clicking on the final link would just refresh the page. Preferred alternative to removing the current-viewed issue title altogether is to include it as text but not a link in the trail. 

I feel somewhat strongly about this but it's also not a hill I'll die on.

**Comment by SgtPooki** [comment]
ok sounds good
