### ISSUE TITLE
Milestone Card hover state: Add outline for emphasis and to indicate clickability

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/Starmaps#71]
**Request**: Add outer stroke to milestone cards hover state when there are children milestones. This will allow users to understand that they can click into each milestone. Relates to #61 

**Note**: If there are no children milestones, there should be no hover state and the milestone card should remain in neutral state. Relates to #62 

**Stroke Color**: #1FA5FF
**Stroke Weight**: 2px

**Prototype recording:**
Shows mouse hovering over each milestone card (in both overview and detailed view). On hover, an outer stroke appears. 

https://user-images.githubusercontent.com/58958327/201191396-3a3225c2-6e09-46c5-97c6-ba8bb40ca181.mov

**Comment by wilkyr31d** [comment]
@juliaxbow can this be P1?

**Comment by juliaxbow** [comment]
I'll let @SgtPooki chime in on how easy this is to accomplish (seems like it should be straightforward but what do I know!) BUT I prefer to leave as P0. As for why:

- It will allow users to understand what they can or can't click into and learn how to interact with the roadmap.
- It will also help avoid #62 (user tries to click into a child milestone but it doesn't behave as expected because it is the final milestone)

**Comment by wilkyr31d** [comment]
Let's rationalize this as part of this thread: https://filecoinproject.slack.com/archives/C0418TBQ9CH/p1668131525690269

I get your argument, but not sure if whole card clickable is the right design anymore based on what I say in that thread

**Comment by wilkyr31d** [comment]
TBF - what you're going for with visual cues is great and maybe is P0 if easy enough - I'm now saying I'm not sure this is the right visual cue if we change how clicks work

**Comment by juliaxbow** [comment]
@SgtPooki per your slack and the convo in this issue, if we need to downgrade this to P1 we can

**Comment by wilkyr31d** [comment]
@juliaxbow - did you land on how to handle the multiple click actions we want? How does that impact this issue?

**Comment by SgtPooki** [comment]
continuing discussion for github link placement in https://github.com/pln-planning-tools/Starmaps/issues/74

**Comment by SgtPooki** [comment]
also related to https://github.com/pln-planning-tools/Starmaps/issues/61
