### ISSUE TITLE
Add link to GitHub source on every page

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/Starmaps#73]
**Details:** 
From every page within StarMaps the user should be able to go to the source GitHub issue. Including it at the same level as the roadmap header will allow for easy access

Inspect in [Figma](https://www.figma.com/file/7l5BAnM9ZDxDJePm3yIJFS/Roadmapping-Tool-MVP?node-id=460%3A3861&t=2WvWiY8XZsUNIsIN-0)

**Text**: 
"View in GitHub" 

**Icon**: 
GitHub Icon

**Color of text and icon**: 
Light Mode #313239
<img width="651" alt="Light Mode Link" src="https://user-images.githubusercontent.com/58958327/201216006-940e7315-efed-4e6b-b985-f7444a08ff71.png">

Dark Mode #D7D7D7
<img width="856" alt="Dark Mode" src="https://user-images.githubusercontent.com/58958327/201215762-4964ab84-b55e-4911-90b0-071bfef18b34.png">

**Comment by wilkyr31d** [comment]
@juliaxbow I'm not sure I understand this one - is this only navigating to the Github issue for the root node of the current view?

**Comment by juliaxbow** [comment]
In the screenshot above, yes - tt would link to the Github issue for the root node. But, as you click into different child milestones, the link would take you to those corresponding issues.  

See the video below at 14 sec, 16 sec, and 18 sec. For each of those child milestones that you view, the "View in GitHub" link  should update. Its positioning and the link text should remain unchanged, though. 

Let me know if this is still unclear.

https://user-images.githubusercontent.com/58958327/201245247-6a2db2eb-9529-4380-8c85-d4bd87a8d76c.mov

**Comment by wilkyr31d** [comment]
Clear as day. I like it!
