### ISSUE TITLE
GitHub Link: Add GitHub Icon to Milestone Cards that Links to source GH Issue

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/Starmaps#74]
**Description**
This is a new recommendation to add the GitHub icon to each milestone card so that users can quickly open tabs and see details about each milestone.
Inspect in [Figma](https://www.figma.com/file/7l5BAnM9ZDxDJePm3yIJFS/Roadmapping-Tool-MVP?node-id=460%3A3861&t=2WvWiY8XZsUNIsIN-0)

**Behavior**
Clicking on the GitHub icon within each milestone card will take you to the issue in GitHub

**Icon**
GitHub Icon

**Color**
Natural State: #8A9097
Hover State: #000000

**Prototype**

https://user-images.githubusercontent.com/58958327/201218349-1ae96e51-45a0-40b1-bb81-adbc36de9aa7.mov

**Comment by wilkyr31d** [comment]
I think this has to be MVP so changing the labels. Need to rationalize bigger picture though: https://filecoinproject.slack.com/archives/C0418TBQ9CH/p1668131525690269

cc @juliaxbow
