### ISSUE TITLE
Remove deprecated `maplight` Vercel integration

### ISSUE THREAD

**Issue by AlexxNica** [pln-planning-tools/Starmaps#83]
We recently moved from the `maplight` account to the `starmaps` one. We should disable the integration for the deprecated `maplight`.

I can do this on my side, just need a check.

cc @wilkyr31d @SgtPooki

**Comment by wilkyr31d** [comment]
If we get to this, great, but putting in P1 bucket for now that we need to get laser focus on P0s

**Comment by AlexxNica** [comment]
Taking this one right now as per @SgtPooki's [request](https://filecoinproject.slack.com/archives/C0418TBQ9CH/p1668464390567759).
