### ISSUE TITLE
Update branding: Use Starmaps.app everywhere

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/Starmaps#84]
we need to update the naming in the following locations:

1. Site header / logo name
2. user guide

#### Old names found and their replacements

|   Old Name  | Replacement name |
|:-----------:|:----------------:|
| Maplight    | Starmaps         |
| Planetarium | Starmaps         |

@juliaxbow is there anything else that needs calling out for this update?

**Comment by SgtPooki** [comment]
lets use "StarMaps" issue

**Comment by juliaxbow** [comment]
I believe this is done now that the user guide has been updated. Closing this issue out.
