### ISSUE TITLE
fix: quarter labels should not be duplicated

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/Starmaps#92]
http://localhost:3000/roadmap/github.com/ipfs/roadmap/issues/102

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/1173416/201821754-829f9048-fc54-4427-ab5a-21e3a3d06074.png">

@juliaxbow I assume we should decrement quarters accordingly? and that we've decided on a hard-coded number of "ticks/labels" at the top?

**Comment by juliaxbow** [comment]
Discussed live. Yes to both questions, though this may change when we get ahold of more roadmaps and can see date ranges

**Comment by whizzzkid** [comment]
Demo:
- Simple: https://starmaps-git-fix-quarter-ticks-ipfs-ignite.vercel.app/roadmap/github.com/ipfs/roadmap/issues/102?view=simple
- Detailed: https://starmaps-git-fix-quarter-ticks-ipfs-ignite.vercel.app/roadmap/github.com/ipfs/roadmap/issues/102?view=detail

**Comment by juliaxbow** [comment]
Reopening as this is still occurring in detailed view

**Comment by SgtPooki** [comment]
@juliaxbow do we have an example issue I can use to see the issue? I'm not seeing it on the simple or detailed view for https://www.starmaps.app/roadmap/github.com/ipfs/roadmap/issues/102

**Comment by juliaxbow** [comment]
https://github.com/filecoin-project/bacalhau/issues/1151

In this instance it looks like it may be happening because all of the milestones have a Q4 ETA. Regardless, it still should show the standard range
