### ISSUE TITLE
feat: Update UI for ViewMode Toggle

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/StarMaps#99]
**Details**
Currently the StarMaps tool has a single hyperlink that allows you to switch between views (views that we're calling "Detailed" and "Overview" for now). This should be updated so that the user can see both selections and toggle between the two views more seamlessly. 

**Font Size & Emphasis:** 
- Active State: 16 Bold
- Inactive State: 16 Light

**Horizontal line:**
- @ 94% text width underneath selection to indicate active state
- 2px weight
- 16px below text

**Other flags:**
- Reid and I agree "Detailed View" / "Overview" or "Simple View" don't capture what's being presented. So flagging that these terms will change.

**Current**
<img width="1672" alt="Screen Shot 2022-11-15 at 1 18 06 AM" src="https://user-images.githubusercontent.com/58958327/201880059-646548a4-3de2-4a9b-86c0-9ca2085fec74.png">

**Proposed**
<img width="856" alt="Dark Mode Link" src="https://user-images.githubusercontent.com/58958327/201877706-1529f59b-e2fe-4814-9fa1-026734935723.png">
<img width="651" alt="Light Mode Link" src="https://user-images.githubusercontent.com/58958327/201877709-932db646-7f1b-4e05-9234-7c386a9f1181.png">

**Proposed in action**

https://user-images.githubusercontent.com/58958327/201881312-148988f1-dcff-4877-aa2a-60381fe392ea.mov

**Comment by SgtPooki** [comment]
note that we should use https://chakra-ui.net/docs/components/tabs/usage for this
